/// <reference types="@cloudflare/workers-types" />

// Env interface is generated by `wrangler types` in worker-configuration.d.ts
// This empty interface serves as a fallback if worker-configuration.d.ts doesn't exist
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface Env {}

declare module "react-router" {
  interface AppLoadContext {
    cloudflare: {
      env: Env;
      ctx: ExecutionContext;
    };
  }
}

export {};
