// Generated by Wrangler by running `wrangler types`
// Simplified for TypeScript compatibility

interface Env {
  PORT: string;
  ROOT_URL: string;
  COOKIE_SECRETS: string;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  DB: D1Database;
  ASSETS: Fetcher;
}
