# fly.toml app configuration file generated for dans-counter-app on 2024-01-20T17:17:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dans-counter-app"
primary_region = "lhr"

[build]

[env]
PORT = "3000"
SUPABASE_URL = "https://sircazunpagzuyjbvzov.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpcmNhenVucGFnenV5amJ2em92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDU3NDU4MTQsImV4cCI6MjAyMTMyMTgxNH0.OH4leSbuEBd0TEr9g88sMb3MlUqqhrE7B8HmEGQdxg8"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[http_service.checks]]
grace_period = "20s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/health"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
